version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0